version: 2
jobs:
  test-and-build:
    environment:
      - _JAVA_OPTIONS: "-Xms512m -Xmx1024m"
    docker:
      - image: cimg/clojure:1.11.1-openjdk-8.0-node
        environment:
          MYSQL_ROOT_PASSWORD: root
      - image: cimg/mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: dbxray_test
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        auth:
          username: nonrecursive
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install default-mysql-client
      - run: sudo apt-get install sqlite3
      - run:
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1

      # core
      - run:
          name: test dbxray clj
          command: clojure -X:test
      - run:
          name: Build dbxray
          command: clojure -T:build jar

      - save-cache:
          paths:
            - ~/bin
            - ~/.m2
          key: donut-{{ checksum "build.clj" }}
      - persist_to_workspace:
          root: ./
          paths:
            - ./
  deploy:
    docker:
      - image: cimg/clojure:1.11.1-openjdk-8.0-node
    steps:
      - checkout
      - restore_cache:
          key: dbxray-{{ checksum "build.clj" }}
      - attach_workspace:
          at: ./
      - run:
          name: Deploy dbxray to clojars
          command: clojure -T:build deploy

workflows:
  version: 2
  build:
    jobs:
      - test-and-build
      - deploy:
          filters:
            branches:
              only:
                - release
          requires:
            - test-and-build
